apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 104387388648.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
        ports:
        - containerPort: 81
        envFrom:
        - configMapRef:
            name: flask-app-config
        - secretRef:
            name: mysql-secret
        env:
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DBHOST