apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final2
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==  # Base64 encoded value of "root_password"
  MYSQL_USERNAME: dXNlcg==                   # Base64 encoded value of "user"
  MYSQL_PASSWORD: dXNlcl9wYXNzd29yZA==       # Base64 encoded value of "user_password"
  DBHOST: bXlzcWwtc2VydmljZQ==               # Base64 encoded value of "mysql-service"
  DATABASE: ZW1wbG95ZWVz                     # Base64 encoded value of "employees"
  DBPORT: MzMwNg==                           # Base64 encoded value of "3306"
