name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Flask app image to Amazon ECR
        env:
          ECR_REGISTRY: 104387388648.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .

      - name: Build, tag, and push MySQL image to Amazon ECR
        env:
          ECR_REGISTRY2: 104387388648.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY2: mysql-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY2/$ECR_REPOSITORY2:$IMAGE_TAG -f Dockerfile_mysql .

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pytest
        run: |
          python -m pip install pytest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure Flask is listed in requirements.txt

      - name: Run tests with pytest
        run: |
          pytest --maxfail=5 --disable-warnings

      - name: Publish to ECR only if tests pass
        if: success()
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY2/$ECR_REPOSITORY2:$IMAGE_TAG
